In [1]:
# Import libraries 
import numpy as np 
import pandas as pd 
# Import label encoder 
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB
import pandas as pd
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score 
from sklearn.metrics import precision_score
from sklearn.metrics import classification_report

# Import dataset 
df = pd.read_csv('/home/devvrat/Documents/Flight_Delay_Prediction/Data/Processed_data15.csv')  

In [2]:
df.shape

(327346, 7)

In [3]:
df.head(10)

year  month  day carrier origin dest  delayed
0  2013      1    1      UA    EWR  IAH        0
1  2013      1    1      UA    LGA  IAH        1
2  2013      1    1      AA    JFK  MIA        1
3  2013      1    1      B6    JFK  BQN        0
4  2013      1    1      DL    LGA  ATL        0
5  2013      1    1      UA    EWR  ORD        0
6  2013      1    1      B6    EWR  FLL        1
7  2013      1    1      EV    LGA  IAD        0
8  2013      1    1      B6    JFK  MCO        0
9  2013      1    1      AA    LGA  ORD        0

In [4]:
columns= ['carrier','dest', 'origin']
le=LabelEncoder()
for i in columns:
     df[i]=le.fit_transform(df[i])

In [5]:
df['carrier'].unique()

array([11,  1,  3,  4,  5,  9, 12, 14, 13,  7,  2,  0,  6,  8, 15, 10])

In [6]:
df['origin'].unique()

array([0, 2, 1])

In [7]:
df['dest'].unique()

array([ 43,  57,  12,   4,  68,  35,  42,  53,  70,  99,  49,  89,  30,
        11,  48,  60,  32,  82,  91,  73,  16,  23,  14,  29,  94,  61,
        92, 103,  58,  88,  81,  98,  95,  79,  24,  47,  21,  55,  74,
        83,  28,  22,  96,  64,  46,  54,  40,  10,   5,  13,  72,  97,
        33,   6,  78,  45,  85,  19,  41,  51,  27,   2,   7,  56,  59,
        37,  26,  15,  80,  38,  36,  52,  69,  84,  87,  71,  90,  67,
        25,  65,  93, 102,  77,  31,  75, 100,   9,  66,  18,  39,  17,
        62,  34,  76,   1,   8,   0,  44,  63,  86,  50,  20, 101,   3])

In [8]:
X = df.iloc[:, 0:6].values # from column(years) to column(distance)
X[0:5]

array([[2013,    1,    1,   11,    0,   43],
       [2013,    1,    1,   11,    2,   43],
       [2013,    1,    1,    1,    1,   57],
       [2013,    1,    1,    3,    1,   12],
       [2013,    1,    1,    4,    2,    4]])

In [9]:
y = df['delayed']
y.head().to_frame()

delayed
0        0
1        1
2        1
3        0
4        0

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3,random_state=3) # 70% training and 30% test

In [11]:
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
gnb = GaussianNB()

#Train the model using the training sets
gnb.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = gnb.predict(X_test)

In [12]:
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Accuracy in percentage:",metrics.accuracy_score(y_test, y_pred)*100)

Accuracy: 0.7196448209848886
Accuracy in percentage: 71.96448209848886


In [13]:
# predicting the trained Classifier to the test
yhat = gnb.predict(X_test)

In [14]:
# Viewing the predicted probabilities of first 10 observations
yhat_prob = gnb.predict_proba(X_test)[:10]

In [15]:
print(classification_report(y_test, yhat))

              precision    recall  f1-score   support

           0       0.72      1.00      0.84     70672
           1       0.00      0.00      0.00     27532

    accuracy                           0.72     98204
   macro avg       0.36      0.50      0.42     98204
weighted avg       0.52      0.72      0.60     98204



/home/devvrat/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
